eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9040/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true
grpc:
  server:
    port: 50051
server:
  port: 9018
spring:
  amqp:
    deserialization:
      trust:
        all: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue: catalogStockQueue
    exchange: catalogStockExchange
    routingkey: routing_key_examp
    virtual-host: /
  cloud:
    config:
      enabled: true
  main:
    allow-bean-definition-overriding: true
  application:
    name: stock-server
  datasource:
    #    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/stockOfProduct2
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validation:
            mode: none
        show-sql: true


