#eureka:
#  client:
#    fetchRegistry: true
#    registerWithEureka: true
#    serviceUrl:
#      defaultZone: http://localhost:9020/eureka
#  instance:
#    instance-id: ${spring.application.name}:${instanceId:${random.value}}
#    preferIpAddress: true
server:
  port: 9013
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/orders
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
grpc:
  client:
    stock-server:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
