server:
  port:
    9002
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9020/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true
spring:
  application:
    name: gatewayService
  cloud:
    config:
      enabled: true
    gateway:
      mvc:
        routes[0]:
          id: catalogservice
          predicates[0]: Path=/api/v1/catalogs/**
          uri: lb://CATALOGSERVICE
        routes[1]:
          id: orderservice
          predicates[0]: Path=/stockservice/api/v1/orders/**
          uri: lb://STOCKSERVICE